name: A workflow for the fibonacci sequence
on: [push, pull_request]

jobs:
  build:
    name: Run the fibonacci algoritm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./fibonacci
        with:
          N_INDEX: "9"
